@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsImlhdCI6MTc3MzMwNDUwMSwiZXhwIjoxNzczMzA4MTAxfQ.uioFjNIjEzWopicorAxJX8n86x88jIYoScWIvBJggBE

  # POST {{baseUrl}}/auth/register
  # Content-Type: application/json

  # {
  #   "organization_id": 4,
  #   "name": "admin",
  #   "email": "admin@mail.com",
  #   "password": "123456",
  #   "role": "admin"
  # }

# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#  "email":"admin@mail.com",
#  "password":"123456"
# }


  
GET {{baseUrl}}/bookings/
Authorization: Bearer {{token}}